some refactoring re. installing ambari-server and discovering nodes in pool when no vols have been created

diff --git a/bin/functions b/bin/functions
--- a/bin/functions
+++ b/bin/functions
@@ -22,6 +22,30 @@ function check_ssh() {
   return 0
 }
 
+# get_ambari_repo: wget the ambari repo file in the correct location.
+function get_ambari_repo(){
+ 
+  local REPO_DIR='/etc/yum.repos.d'
+  local REPO_URL='http://public-repo-1.hortonworks.com/ambari/centos6/1.x/updates/1.4.4.23/ambari.repo'
+  local out; local err; local errcnt=0
+
+  [[ -d $REPO_DIR ]] || mkdir -p $REPO_DIR
+  cd $REPO_DIR
+
+  out="$(wget $REPO_URL 2>&1)"
+  err=$?
+  if (( err != 0 )) ; then
+    echo "ERROR $err: ambari repo wget: $out"
+    ((errcnt++))
+  fi
+
+  cd - >/dev/null
+
+  (( errcnt > 0 )) && return 1
+  return 0
+}
+
+
 # vol_exists: invokes gluster vol info to see if VOLNAME exists. Returns 1 on
 # errors. 
 # Args:
