moved vol_exists() to functions and misc refactoring

diff --git a/bin/functions b/bin/functions
--- a/bin/functions
+++ b/bin/functions
@@ -48,3 +48,20 @@ function check_ssh() {
   (( errcnt > 0 )) && return 1
   return 0
 }
+
+# vol_exists: invokes gluster vol info to see if VOLNAME exists. Returns 1 on
+# errors. $1=volume name
+function vol_exists() {
+
+  local vol="$1"
+  local err
+
+  gluster volume info $VOLNAME >& /dev/null
+  err=$?
+  if (( err != 0 )) ; then
+    echo "ERROR $err: vol info error on \"$VOLNAME\", volume may not exist"
+    return 1
+  fi
+  return 0
+}
+
