do ntp time sync across nodes. Don't start/stop ntpd per LLNL advice

diff --git a/bin/functions b/bin/functions
--- a/bin/functions
+++ b/bin/functions
@@ -230,6 +230,73 @@ function is_ip_addr() {
   return 1 # false
 }
 
+# ntp_time_sync_check: return 0 if the time drift across the passed-in nodes is
+# less than the WARN threshold. Return 1 if the time drift across the nodes is 
+# between the WARN and ERROR thresholds. Return 0 if the time drift is less than
+# the WARN threshold.
+function ntp_time_sync_check() {
+
+  # logic below supports a WARN threshold > 1 sec. When WARN=1 then we return 0
+  # immediately if the sorted/uniq times array has only a single entry
+  local WARN_DRIFT=1 # second
+  local ERR_DRIFT=5  # seconds
+  local node; local times=(); local diff; local errcnt=0
+
+  for node in $@; do # current times in seconds since 1970-01-01 00:00:00 UTC
+      times+=($(ssh $node "date +%s"))
+      (( $? != 0 )) && ((errcnt++))
+  done
+  if (( errcnt > 0 || ${#times[@]} == 0 )) ; then # can't get time from 1+ nodes
+    echo "\"date +%s\" failed on every node"
+    return 2
+  fi
+
+  times=($(printf '%s\n' "${times[@]}" | sort -u)) # sorted, uniq times
+  debug "sorted/uniq times across nodes ($*): ${times[*]} (seconds)"
+
+  if (( ${#times[@]} == 1 )) ; then # 1 entry means all times w/in <1 sec
+    echo "time differs across nodes by less than 1 second"
+    return 0
+  fi
+
+  diff=$((${times[${#times[@]}-1]} - ${times[0]})) # high-low in secs
+
+  if (( diff >= ERR_DRIFT )) ; then
+    echo "time differs across nodes ($*) by more than $ERR_DRIFT seconds"
+    return 2 # error
+  elif (( diff >= WARN_DRIFT )) ; then
+    echo "time differs across nodes ($*) by between $WARN_DRIFT and $ERR_DRIFT seconds"
+    return 1 # warning
+  fi
+
+  echo "time differs across nodes by less than $WARN_DRIFT seconds"
+  return 0
+}
+
+# ntpd_running: verify that ntpd is running and persisted on this node.
+function ntpd_running() {
+
+  local errcnt=0
+
+  # is ntpd configured to run on reboot?
+  chkconfig ntpd 
+  if (( $? != 0 )); then
+    echo "ERROR: ntpd not configured to run on reboot"
+    ((errcnt++))
+  fi
+
+  # verify that ntpd is running
+  ps -C ntpd >& /dev/null
+  if (( $? != 0 )) ; then
+    echo "ntpd is not running"
+    ((errcnt++))
+  fi
+
+  (( errcnt > 0 )) && return 1
+  echo "ntpd is running..."
+  return 0
+}
+
 # quiet: call display() using LOG_QUIET. $1 can be an echo option or the msg.
 function quiet() {
 
