some refactoring around setting selinux and including the ambari server

diff --git a/bin/functions b/bin/functions
--- a/bin/functions
+++ b/bin/functions
@@ -253,6 +253,33 @@ function quiet() {
   display $opt "$1" $LOG_QUIET
 }
 
+# setup_selinux: set selinux on localhost to permissive mode, which seems to be
+# a HDP requirement. Persist this setting. Returns 1 on errors.
+function setup_selinux() {
+
+  local err
+  local conf='/etc/sysconfig/selinux' # symlink to /etc/selinux/config
+  local selinux_key='SELINUX='
+  local permissive='permissive'
+
+  # set selinux to permissive (audit errors reported but not enforced)
+  setenforce $permissive 2>&1
+
+  # keep selinux permissive on reboots
+  if [[ ! -f $conf ]] ; then
+    echo "WARN: SELinux config file $conf missing"
+    return # nothing more to do...
+  fi
+
+  # config SELINUX=permissive which takes effect the next reboot
+  sed -i -e "/^$selinux_key/c\\$selinux_key$permissive" $conf
+  err=$?
+  if (( err != 0 )) ; then
+    echo "ERROR $err: trying to set selinux to permissive in $conf"
+    return 1
+  fi
+}
+
 # uniq_nodes: output the unique nodes from the list of nodes provided.
 # $@=list of nodes.
 function uniq_nodes() {
